#! /bin/sh
# read epubs in vim

# Storage dir:
	EPUBSTORAGE="$XDG_DATA_HOME/epr"
	mkdir -p "$EPUBSTORAGE"

# Opening funct:
	OpenEpub() {
		nvim "$EPUBSTORAGE/$EPUBNAME"
	}

# Open last and help
	[ -z "$1" ] && EPUBNAME=$(cat "$EPUBSTORAGE/lastName") && OpenEpub ||\
	[ "$1" = "-h" ] && printf '%s\n' \
        '| $1 = "file" = "Open File"                    |'\
        '| $1 = "--fp" = "Use when providing full path" |'\
        '| $1 = "-h"   = "Show Help"                    |'\
        '| $1 = ""     = "Last File" and/or "Show Help" |' && exit

# Set up vars
	[ "$1" = "--fp" ] \
		&& EPUBPATH="$2" \
		|| EPUBPATH="$(readlink -f *$1*)"
	EPUBNAME="$(basename "$EPUBPATH" | sed -e 's/\.[^.]*$/.txt/')"
	echo "$EPUBNAME" > "$EPUBSTORAGE/lastName"

# Open last or make new
	[ -e "$EPUBSTORAGE/$EPUBNAME" ] \
		|| epub2txt -w 0 "$EPUBPATH" > "$EPUBSTORAGE/$EPUBNAME"
	OpenEpub
