#! /bin/sh

# Open last and help
	if [ -z "$1" ] || [ "$1" = "-h" ] ; then
		printf '%s\n' \
        	'| $1 = "file" 	   = "Repack File"			|'\
        	'| $1 = "--fp" 	   = "Use when providing full path"	|'\
        	'| $1 = "-h" or "" = "Show Help"	r		|' && exit
	fi
# Set up vars:
	EPUBSTORAGE="$XDG_DATA_HOME/epr"
	mkdir -p "$EPUBSTORAGE"
	ETRPOUT="$HOME/dl"
	ETRPSTORAGE="/tmp/etrp"
	EPUBFILES=$(echo "$EPUBSTORAGE"/*)
	[ "$1" = "--fp" ] \
		&& EPUBPATH="$2" \
		|| EPUBPATH="$(readlink -f *$1*)"
	ETRPNAME="$(basename "$EPUBPATH" | sed -e 's/\.[^.]*$//')"
	EPUBNAME="$(basename "$EPUBPATH" | sed -e 's/\.[^.]*$/.txt/')"
	SLPITLINE="200"
# Make new
	if [ -e "$EPUBSTORAGE/$EPUBNAME" ] ; then
		echo "$EPUBFILES" | grep "$EPUBNAME" 2>&1 /dev/null \
	else
		epub2txt -w 0 "$EPUBPATH" > "$EPUBSTORAGE/$EPUBNAME"
	fi
# Repack everything
	if [ -e "$EPUBSTORAGE" ] ; then
		rm -rf "$ETRPSTORAGE"/* \
	else
		mkdir "$ETRPSTORAGE" 2> /dev/null
	fi
	mkdir -p "$ETRPSTORAGE/$ETRPNAME" ; cd "$ETRPSTORAGE/$ETRPNAME"

	split "$EPUBSTORAGE/$EPUBNAME" -l "$SLPITLINE"
	for f in * ; do mv "$f" "$f.txt" ; done
	zip -r9q "$ETRPOUT/$ETRPNAME.zip" "$ETRPSTORAGE/$ETRPNAME"
