#! /bin/sh

PMBROWSER="firefox"
[ -n "$1" ] \
	&& ARGS="$@" \
	|| ARGS=$(xclip -selection clipboard -o)
PMcmd(){
	paru -Si $1
}
URLcmd(){
	grep URL $@ | cut -d " " -f15
}

for PKGNAME in $ARGS ; do
	$PMBROWSER "$( PMcmd $PKGNAME | URLcmd )"
done
