#! /bin/sh
# grabs info from paru and puts it in the browser

#vars
	PMBROWSER="firefox"
	[ -n "$1" ] \
		&& ARG="$@" \
		|| ARGS=$(xclip -selection clipboard -o)

# Functs
	PMcmd(){
		paru -Si $1
	}

	URLcmd(){
		grep URL $@ | cut -d " " -f15
	}

# run
	for PKGNAME in $ARGS ; do
		$PMBROWSER "$( PMcmd $PKGNAME | URLcmd )"
	done
