#! /bin/sh
# legicy alias for rm, maybe ill remake it eventually

rm -vI $* && exit

echo "Preform "rmdir $*" instead? "

read -r -p '[y/N]: ' RMDYN

[ "$RMDYN" = "${RMDYN#[Yy]}" ] && echo "rmdir $* canceled" && exit

rmdir $* && echo "Removed Directory"  && exit

echo "Preform "rm -r $*"  insted? "

read -r -p '[y/N]: ' RMRYN

[ "$RMRYN" != "${RMRYN#[Yy]}" ] && rm -r $* && echo "Removed Directory and Contsents"  && exit

echo "rm -r $* canceled"
