#!/bin/bash

# funct
Unscrer(){
	for FILESPC in *	; do
		FILEUND="${FILESPC// /_}"
		[ "$FILEUND" != "$FILESPC" ] && \
		if [ -e "$FILEUND" ] ; then
			echo not renaming \""$FILESPC"\" because \""$FILEUND"\" already exists
		else
			mv "$FILESPC" "$FILEUND" && echo moving "$FILESPC" to "$FILEUND"
		fi
	done
}

# run
if [ "$1" = "-R" ] 	; then

	SDIR="$(pwd)"
	NDIRS="$(find -type d .)"
	for CDIR in $NDIRS ; do
		cd "$SDIR/$CDIR"
		# FILENAME=$(echo *)
		Unscrer
	done
elif [ -n "$1" ]	; then
	# FILENAME="$@"
	Unscrer
else
	# FILENAME=$(ls *)
	Unscrer
fi
