#!/bin/sh

	cd "$(xdg-user-dir DOWNLOAD)"
	mkdir -p zipper/archive

UZcleanu(){
	cd zipper
	underscored

	for MVFILE in ./* ; do
		case "$(file --mime-type "$MVFILE" -b)" in
			application/epub+zip) mkdir -p epub ; mv "$MVFILE" epub ;;
		esac
	done
}

Uzip(){
	for ARCHIVE in ./* ; do
		$ASVAR "$ARCHIVE" -o zipper &&
			mv "$ARCHIVE" zipper/archive
	done
}


case $1 in
	"nc"|"--nc")
		PASS="thatnovelcorner.com"
		ASVAR="unar -password $PASS"
		Uzip
		UZcleanu
		;;

	"p"|"-p")
		if [ -z "$2" ] ; then
			read -r -p 'Password:' PASS
		else
			PASS="$2"
		fi
		ASVAR="unar -password $PASS"
		Uzip
		UZcleanu
		;;

	*)
		ASVAR="unar"
		Uzip
		UZcleanu
esac
