#!/bin/sh

# Kill the old timer
pkill bgctimer

# Get the current hour, month, date, and minute
hour=$(date '+%-H')
month=$(date '+%-m')
date=$(date '+%-e')
minute=$(date '+%-M')

# Determine the season based on the month
case $month in
    1|2)  season='wntr' ;;
    3|4|5) season='sprg' ;;
    6|7|8) season='sumr' ;;
    9|11)  season='fall' ;;
    10)    season='hldy/hlwn' ;;
    12)    if [ $date -lt 25 ]; then
                season='hldy/crms'
            else
                season='wntr'
            fi
            ;;
    *)     echo "$month is not a valid month" ; exit 1
esac

# Determine the time of day and set the variables
if [ $hour -ge 0 ] && [ $hour -lt 3 ]; then
    # Night time
    vbg='nbg'
    time_until_next_bg=$(( (4-$hour)*60-$minute ))
elif [ $hour -ge 3 ] && [ $hour -lt 9 ]; then
    # Morning
    vbg='mbg'
    time_until_next_bg=$(( (9-$hour)*60-$minute ))
elif [ $hour -ge 9 ] && [ $hour -lt 16 ]; then
    # Daytime
    vbg='dbg'
    time_until_next_bg=$(( (16-$hour)*60-$minute ))
elif [ $hour -ge 16 ] && [ $hour -lt 20 ]; then
    # Evening
    vbg='ebg'
    time_until_next_bg=$(( (20-$hour)*60-$minute ))
elif [ $hour -ge 20 ] && [ $hour -lt 24 ]; then
    # Night time
    vbg='nbg'
    time_until_next_bg=$(( (24-$hour)*60-$minute ))
else
    echo "$hour is not a valid hour" ; exit 1
fi

# Link the new background image
if [ -n "$1" ]; then
    ln -sf "$(readlink -f "$1")" "$XDG_DATA_HOME/bgc/$season/$vbg"
fi

# Set the new background image
setbg "$XDG_DATA_HOME/bgc/$season/$vbg"

# Set the timer for the next background change
echo $time_until_next_bg | bgctimer
