#! /bin/sh
# changes wallpaper based on time

# Kill old time
	pkill bgctimer

# grab the time
	## | DN=Hour | TY=Month | DM=Date | MN=Minute |
	DN=$(date '+%-H')
	TY=$(date '+%-m')
	DM=$(date '+%-e')
	MN=$(date '+%-M')

# Time of year
case $TY in
	1|2) 	SZN='wntr'	;;
	3|4|5)	SZN='sprg'	;;
	6|7|8)	SZN='sumr'	;;
	9|11)	SZN='fall'	;;
	10)	SZN='hldy/hlwn' ;;
	12)	[ $DM -lt 25 ] \
			&& SZN='hldy/crms' \
			|| SZN='wntr'	;;
	*) echo "$TY not a valid season" ; exit
esac

# Find current 1/4 and set vars
case $DN in
	0|1|2)
		VBG=nbg && TETBG=$(( (4-$DN)*60-$MN ))	;;
	3|4|5|6|7|8)
		VBG=mbg && TETBG=$(( (9-$DN)*60-$MN ))	;;
	9|10|11|12|13|14|15)
		VBG=dbg && TETBG=$(( (16-$DN)*60-$MN ))	;;
	16|17|18|19)
		VBG=ebg && TETBG=$(( (20-$DN)*60-$MN ))	;;
	20|21|22|23)
		VBG=nbg && TETBG=$(( (28-$DN)*60-$MN ))	;;
	*) echo "$DN not a valid time" ; exit
esac

# Run commands
	[ -n "$1" ] && ln -sf "$(readlink -f "$1")" "$XDG_DATA_HOME/bgc/$SZN/$VBG"
	setbg "$XDG_DATA_HOME/bgc/$SZN/$VBG"
	echo $TETBG | bgctimer
