#!/bin/sh

# This script does the following:
#	Run by itself, set the wallpaper (at X start).
#	If given a file, set that as the new wallpaper.
#	If given a directory, choose random file in it.
#	If wal is installed, also generates a colorscheme.

# Location of link to wallpaper link.

BGLOC="$XDG_DATA_HOME/bg"

[ -f "$1" ] \
	&& ln -sf "$(readlink -f "$1")" "$BGLOC" \
	&& notify-send -i "$BGLOC" "Changing wallpaper..."

[ -d "$1" ] \
	&& ln -sf "$(find "$(readlink -f "$1")" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$BGLOC" \
	&& notify-send -i "$BGLOC" "Random Wallpaper chosen."


# If pywal is installed, use it.
wal -i "$(readlink -f "$BGLOC")" -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun" >/dev/null 2>&1

pidof dwm >/dev/null && xdotool key super+F12

for DSPLY in $(xrandr | grep " connected " | cut -d ' ' -f1) ; do
	PDREZ="$(xrandr | awk '{
			if(/^'$DSPLY'/) {
				print $0;
				m="t";
			} else if(m == "t"){
				if (/^[a-zA-Z]/){
				        exit
				} else {
				        print $0
				}
			}
		}' | grep '*' | cut -d ' ' -f4)"
	PDWTH="$(echo "$PDREZ" | cut -d 'x' -f1)"
	PDHGT="$(echo "$PDREZ" | cut -d 'x' -f2)"

	BGDIM=$(identify -format "%w %h" "${BGLOC}")
	if [ "$(echo $BGDIM | cut -d ' ' -f1)" -ge "$PDWTH" -a "$(echo $BGDIM | cut -d ' ' -f2)" -ge "$PDHGT" ] ; then
		XWPARG="$XWPARG --output $DSPLY --zoom $BGLOC"
	else
		XWPARG="$XWPARG --output $DSPLY --maximize $BGLOC"
	fi
done
xwallpaper $XWPARG
