#!/bin/zsh

# Kill old time
	pkill bgctimer
# grab the time
	# | DN=Hour | TY=Month | DM=Date |
	DN=$(date '+%-H')
	TY=$(date '+%m')
	DM=$(date '+%e')
# Time of year
	case $TY in
		01|02) 		SZN='wntr'	;;
		03|04|05)	SZN='sprg'	;;
		06|07|08)	SZN='sumr'	;;
		09|11)		SZN='fall'	;;
		10)		SZN='hldy/hlwn' ;;
		12)	 [ $DM -lt 25 ] \
				&& SZN='hldy/crms' \
				|| SZN='wntr'	;;
		*) echo "$TY not a valid season" ; exit
	esac


# Find current 1/4 andset vars
	case $DN in
		00|01|02)
			VBG=nbg && TETBG=$(( (4-$DN)*60-$(date '+%-M') ))	;;
		03|04|05|06|07|08)
			VBG=mbg && TETBG=$(( (9-$DN)*60-$(date '+%-M') ))	;;
		09|10|11|12|13|14|15)
			VBG=dbg && TETBG=$(( (16-$DN)*60-$(date '+%-M') ))	;;
		16|17|18|19)
			VBG=ebg && TETBG=$(( (20-$DN)*60-$(date '+%-M') ))	;;
		20|21|22|23)
			VBG=nbg && TETBG=$(( (28-$DN)*60-$(date '+%-M') ))	;;
		*) echo "$DN not a valid time" ; exit
	esac

# Run commands
	[ -n "$1" ] && ln -sf "$(readlink -f "$1")" $XDG_DATA_HOME/bgc/$SZN/$VBG
	setbg $XDG_DATA_HOME/bgc/$SZN/$VBG
	echo $TETBG | bgctimer
