#! /bin/sh
# little thing to fix my wacam so it only on the priomary moniter

PDSPLY="$(xrandr | grep -w primary | cut -d " " -f1)"

for INPUT in $(xinput | grep "Wacom" | grep -v "Finger touch" | cut -c 55-56) ; do
	xinput map-to-output $INPUT $PDSPLY
done
