#! /bin/sh

EPUBSTORAGE="/tmp/epr"

OpenEpub() {
	fold -s -w $(tput cols) /tmp/epr/$EPUBNAME | less
}

ls $EPUBSTORAGE > /dev/null || mkdir $EPUBSTORAGE

[ -z "$1" ] && EPUBNAME=$(cat ls $EPUBSTORAGE/lastName) && OpenEpub ||\
[ "$1" = "-h" ] && echo '| $1 = "file" = "Open File"		       |
| $1 = "-h"   = "Show Help"		       |
| $1 = ""     = "Last File" and/or "Show Help" |' && exit

EPUBPATH="$(readlink -f *$1*)"
EPUBNAME="$(echo $(basename $EPUBPATH ) | sed -e 's/\.[^.]*$/.txt/')"

ls $EPUBSTORAGE | grep $EPUBNAME && OpenEpub && exit

echo "$EPUBNAME" > $EPUBSTORAGE/lastName

epub2txt -w 0 $EPUBPATH > $EPUBSTORAGE/$EPUBNAME

OpenEpub
