#! /bin/sh

# Open last and help
	[ -z "$1" ] || [ "$1" = "-h" ] && echo -e \
	' | $1 = "file"     = "Repack File"		     |\n'\
	'| $1 = "--fp" 	   = "Use when providing full path" |\n'\
	'| $1 = "-h" or "" = "Show Help"		    |' && exit
# Set up vars:
	EPUBSTORAGE="$XDG_DATA_HOME/epr"
	ETRPOUT="$HOME/dl"
	ETRPSTORAGE="/tmp/etrp"
	EPUBFILES=$(ls $EPUBSTORAGE) || mkdir $EPUBSTORAGE
	[ "$1" = "--fp" ] \
		&& EPUBPATH="$2" \
		|| EPUBPATH="$(readlink -f *$1*)"
	ETRPNAME="$(basename $EPUBPATH  | sed -e 's/\.[^.]*$//')"
	EPUBNAME="$(basename $EPUBPATH  | sed -e 's/\.[^.]*$/.txt/')"
	SLPITLINE="200"
# Make new
	echo $EPUBFILES | grep $EPUBNAME &> /dev/null \
		|| epub2txt -w 0 $EPUBPATH > $EPUBSTORAGE/$EPUBNAME
# Repack everything
	mkdir $ETRPSTORAGE 2>/dev/null || rm -rf $ETRPSTORAGE/*
	mkdir -p $ETRPSTORAGE/$ETRPNAME ; cd $ETRPSTORAGE/$ETRPNAME

	split $EPUBSTORAGE/$EPUBNAME -l $SLPITLINE
	for f in * ; do mv "$f" "$f.txt" ; done
	zip -r9q $ETRPOUT/$ETRPNAME.zip $ETRPSTORAGE/$ETRPNAME