#! /bin/sh

[ "$1" = "vi" ] && (
xmodmap -e 'keycode 43 = 0xff51'
xmodmap -e 'keycode 44 = 0xff54'
xmodmap -e 'keycode 45 = 0xff52'
xmodmap -e 'keycode 46 = 0xff53'
) && exit
[ "$1" = "zxcv" ] && (
xmodmap -e 'keycode 53 = 0xff51'
xmodmap -e 'keycode 54 = 0xff54'
xmodmap -e 'keycode 55 = 0xff52'
xmodmap -e 'keycode 56 = 0xff53'
) && exit

xmodmap -e 'keycode 43 = 0x68'
xmodmap -e 'keycode 44 = 0x6a'
xmodmap -e 'keycode 45 = 0x6b'
xmodmap -e 'keycode 46 = 0x6c'
xmodmap -e 'keycode 53 = 0x7a'
xmodmap -e 'keycode 54 = 0x78'
xmodmap -e 'keycode 55 = 0x63'
xmodmap -e 'keycode 56 = 0x76'
