#! /bin/sh


# Storage dir:
	EPUBSTORAGE="$XDG_DATA_HOME/piv"
	[ -e $EPUBSTORAGE ] || mkdir $EPUBSTORAGE

# Opening funct:
	OpenEpub() {
		sxiv -bfr $EPUBSTORAGE/$EPUBNAME
	}

# Open last and help
	[ -z "$1" ] && EPUBNAME=$(cat $EPUBSTORAGE/lastName) && OpenEpub ||\
	[ "$1" = "-h" ] && printf '%s\n' \
        '| $1 = "file" = "Open File"                    |'\
        '| $1 = "--fp" = "Use when providing full path" |'\
        '| $1 = "-h"   = "Show Help"                    |'\
        '| $1 = ""     = "Last File" and/or "Show Help" |' && exit

# Set up vars
	[ "$1" = "--fp" ] \
		&& EPUBPATH="$2" \
		|| EPUBPATH="$(readlink -f *$1*)"
	EPUBNAME="$(echo $(basename $EPUBPATH ) | sed -e 's/\.[^.]*$//')"
	echo "$EPUBNAME" > $EPUBSTORAGE/lastName

# Open last or make new
	[ -e "$EPUBSTORAGE/$EPUBNAME" ] \
		|| unzip -LL  $EPUBPATH *.jpg *.png *.jpeg -d $EPUBSTORAGE/$EPUBNAME 2>&1 /dev/null

# Rotate &open
	[ "$2" = "-r" ] \
		&& xrandr --output eDP1 --rotate left \
		&& OpenEpub \
		&& xrandr --output eDP1 --rotate normal \
		&& exit
	OpenEpub
