#! /bin/sh

# Open last and help
    [ -z "$1" ] && sxiv -bfr /tmp/piv/* || \
    [ "$1" = "-h" ] && echo -e \
    ' | $1 = "file" = "Open File"		        |\n'\
    '| $1 = "-h"   = "Show Help"		        |\n'\
    '| $1 = ""     = "Last File" and/or "Show Help" |\n'\
    '| $2 = "-r"   = "Rotate Display Left"          |' && exit
# Set up files
    mkdir /tmp/piv 2>/dev/null || rm -r /tmp/piv/*
    unzip -LL "*$1*" *.jpg *.png *.jpeg -d /tmp/piv >/dev/null
# Rotate
    [ "$2" = "-r" ] && xrandr --output eDP1 --rotate left && sxiv -bfr /tmp/piv/* && xrandr --output eDP1 --rotate normal && exit
# Run
    sxiv -bfr /tmp/piv/*