#!/bin/sh

# This script does the following:
#	Run by itself, set the wallpaper (at X start).
#	If given a file, set that as the new wallpaper.
#	If given a directory, choose random file in it.
#	If wal is installed, also generates a colorscheme.

# Location of link to wallpaper link.

BGLOC="${XDG_DATA_HOME:-$HOME/.local/share/}/bg"

ln -sf $BGLOC $HOME/.config/wall.png

[ -f "$1" ] \
	&& ln -sf "$(readlink -f "$1")" "$BGLOC" \
	&& notify-send -i "$BGLOC" "Changing wallpaper..."

[ -d "$1" ] \
	&& ln -sf "$(find "$(readlink -f "$1")" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$BGLOC" \
	&& notify-send -i "$BGLOC" "Random Wallpaper chosen."


# If pywal is installed, use it.
wal -i "$(readlink -f "$BGLOC")" -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun" >/dev/null 2>&1 \

pidof dwm >/dev/null && xdotool key super+F12

BGDIM=$(identify -format "%w %h" "${BGLOC}")
[ "$(echo $BGDIM | cut -d ' ' -f1)" -ge "1920" -a "$(echo $BGDIM | cut -d ' ' -f2)" -ge "1080" ] \
	&& xwallpaper --zoom "$BGLOC" \
	|| xwallpaper --maximize "$BGLOC"
