#!/bin/sh

# Setup vars
	# Data home
	SFSMNT="$HOME/.local/mnt"
	SFSARGS="$@"
	SDLOG=$SFSMNT/known_dir_log
# Setup Functs
	# Start up sshfs
	SUSfs(){
		for CSMADDR in $(cat $SDLOG)
		do
			Stest $CSMADDR && sshfs -o transform_symlinks $CSMADDR:/ $SFSMNT/$CSMADDR \
				|| echo "$CSMADDR timed-out connecting" >&2
		done
	}
	# Make new dirs for sshfs
	MkSfsDir(){
		for CMDIR in $SFSARGS
		do
			SNADD=$(grep "^$CMDIR$" $SDLOG 2> /dev/null)
			if [ -z "$SNADD" ] ; then
				Stest $CMDIR \
					&& mkdir $SFSMNT/$CMDIR \
					&& echo $CMDIR >> $SDLOG \
					|| echo "$CMDIR timed-out so was not added" >&2
			else
			echo "$CMDIR is already in log" >&2
			fi
		done
	}
	# Kill old prosses
	KlSfs(){
		for SDKL in $(cat $SDLOG)
		do
			$( pkill -9 sshfs
			fusermount -uzq $SFSMNT/$SDKL ) && DIDSMTHN="y"
		done
	}
	# test ssh connection
	Stest(){
		UPDWN=$(ssh -qo ConnectTimeout=4 $1 exit ; echo $?)
		[ "$UPDWN" = "1" ] && return 0 || return 1
	}
# Run everything
	 if mkdir $SFSMNT 2> /dev/null ; then
		 MkSfsDir && SUSfs && exit
	 elif [ -z "$1" ] ; then
		 KlSfs ; SUSfs && exit
	 elif [ "$1" != "-k" ] ; then
		 KlSfs ; MkSfsDir && SUSfs && exit
	 fi
	KlSfs && exit
	[ "$DIDSMTHN" != "y" ] && echo "Nothing to do"