#!/bin/sh

# Setup vars
	# Data home
	SFSMNT="/opt/sshfs-mnt"
	SFSARGS="$@"
	SDLOG="$(cat $SFSMNT/log)"
# Setup Functs
	# Start up sshfs
	SUSfs(){
		for CSMADDR in $SDLOG
		do
			sshfs -o transform_symlinks $CSMADDR:/ $SFSMNT/$CSMADDR
		done
	}
	# Make new dirs for sshfs
	MkSfsDir(){
		for CMDIR in $SFSARGS
		do
			mkdir $SFSMNT/$CMDIR
			echo $CMDIR >> $SFSMNT/log
		done
	}
	# Kill old prosses
	KlSfs(){
		for SDKL in $SDLOG
		do
			pkill -9 sshfs
			fusermount -uzq $SFSMNT/$SDKL
		done
	}
# Run everything
	mkdir $SFSMNT 2> /dev/null && $(
		MkSfsDir && SUSfs) && exit
	[ -z "$1" ] && $(
		KlSfs ; SUSfs)&& exit
	[ "$1" != "-k" ] && $(
		KlSfs ; MkSfsDir && SUSfs) && exit
	KlSfs || echo "Nothing to do"