#! /bin/sh

if [ -z "$1" ]
then
	exit
elif [ -z "$2" ]
then
	TIMER=$1
elif [ -z "$3" ]
then
	TIMER=$(($1+$2*60))
else
	TIMER=$(($1+$2*60+$3*3600))
fi

termdown $TIMER | lolcat || exit

echo Timer Done

while true
do
	paplay /home/share/.asset/t_chime.wav
	sleep .5
done
