#! /bin/sh

TPNAME="SynPS/2 Synaptics TouchPad"
STPSTAT=$(xinput list-props "$TPNAME")
TVNS="DEVE NASE DWTE"
DEVE="Device"
NASE="Natural Scrolling"
DWTE="Disable While Typing"

TGLtp(){
	GBDSTAT=$(echo "$STPSTAT" | grep "$1 Enabled (")
	TGLID=$(echo "$GBDSTAT" | cut -d "(" -f2 | cut -d ")" -f1)

	[ "$(echo "$GBDSTAT" | tail -c 2)" = "1" ] && TGLSTAT="0" || TGLSTAT="1"

	xinput --set-prop "$TPNAME" $TGLID $TGLSTAT
}

HLPmsg(){
	for GBST in $TVNS ; do
		GBDSTAT=$(echo "$STPSTAT" | grep "$(eval "echo \"\$$GBST\"") Enabled (")
		[ "$(echo "$GBDSTAT" | tail -c 2)" = "1" ] \
			&& eval "TG$GBST='On '"\
			|| eval "TG$GBST='Off'"
	done
	MSPD=$(echo "$STPSTAT"\
		| grep "Coordinate Transformation Matrix"\
		|cut -d ' ' -f12)
	SDMP="x$(echo "scale=2;1/$MSPD" | bc)"

	printf '%s\n' \
		"| \$1 	   =  \"-h\" or \"--help\"  = 	   Display help and status	    |"\
		"| \$1 	   =  \"-k\" 		= Toggle $DEVE			Stat: $TGDEVE   |"\
		"| \$1 	   =  \"-n\" 		= Toggle $NASE	Stat: $TGNASE   |"\
		"| \$1	   =  \"-p\" 		= Toggle $DWTE	Stat: $TGDWTE   |"\
		"| \$1 & \$2  =  \"-s (multiplier)\" = Set    Mouse Speed		Stat: $SDMP |"

	exit
}


case  $1  in
	"-h"|"--help") HLPmsg ;;
	"-k")	TGLtp "$DEVE" ;;
	"-n") 	TGLtp "$NASE" ;;
	"-p") 	TGLtp "$DWTE" ;;
	"-s")	xinput --set-prop "$TPNAME" 'Coordinate Transformation Matrix' 1 0 0 0 1 0 0 0 $(echo "scale=6;1/$2" | bc) ;;
	*) HLPmsg
esac
