#! /bin/sh
#dmenue/sxiv w2x script for batch upscaling

#vars
	FNAME="$(basename "$1")"
	FDIR="$(dirname -- "$1")"
	CTNAME="$(echo $FNAME | rev | cut -d '.' -f 2-| rev)"
	# opts for dmenu  , could probaly make this less ugly with a for loop orsomthing, but this is easier
	TLIST="done\n2x-1n\n2x0n\n2x1n\n2x2n\n2x3n\n4x-1n\n4x0n\n4x1n\n4x2n\n4x3n\n8x-1n\n8x0n\n8x1n\n8x2n\n8x3n\n16x-1n\n16x0n\n16x1n\n16x2n\n16x3n\n32x-1n\n32x0n\n32x1n\n32x2n\n32x3n\n1x-1n\n1x0n\n1x1n\n1x2n\n1x3n"

#main shit
	## grab versions
	while [ "$(echo $VERS | rev | cut -d ' ' -f1 | rev)" != "done" ] ; do
		VERS="$VERS $(printf "$TLIST" \
			| dmenu -r -p "Chose which versions to make and select 'done' when complete")"
	done

	#do all the upscaling
	for OPTS in $(printf '%s' "$VERS") ; do
		# check if everything is done
		[ "$OPTS" = "done" ] && notify-send "Finished making versions" && break

		notify-send "Working on $OPTS"

		# format everything and put in vars
		MULT="$(echo $OPTS | cut -d 'x' -f1 -)"
		NOISE="$(echo $OPTS | cut -d 'x' -f2 - | cut -d 'n' -f1 -)"
		NWNAME=""$CTNAME"_"$OPTS".png"

		# run upscaler
		waifu2x-ncnn-vulkan -i "$FDIR/$FNAME" -n $NOISE -s $MULT -f png -o "$FDIR/$NWNAME"
	done

	# inspect and clean
	mkdir -p $FDIR/.2x_archive
	sxiv $FDIR/$CTNAME* && mv $FDIR/$FNAME $FDIR/.2x_archive
